apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  # This makes the service accessible outside the cluster
  type: NodePort
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      # The port you access from the outside
      port: 80
      # The port the container listens on (from Nginx)
      targetPort: 80
